allowBuilds:
  "@parcel/watcher": true
  better-sqlite3: true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true

# -------------------------
# Engine & Environment Settings
# -------------------------
engineStrict: true
pmOnFail: warn
shellEmulator: true

# -------------------------
# Security Policies
# -------------------------
# Enforce a 3-day (4320 minutes) cooldown period for all new packages
# 1 day = 1440, 3 days = 4320, 7 days = 10080
minimumReleaseAge: 4320
blockExoticSubdeps: true
# trustPolicy: no-downgrade
